
name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go v1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          go env -w GO111MODULE=on
          go env -w GOPATH=$GOROOT
          go get -u github.com/gobuffalo/packr/packr
          ls -l $GOPATH/bin
          go env
          packr --help
